這幾工請 Roo 修正問題毋閣猶無修好勢
Tab pressed at: 76.40275603433227 app.js:216:21
Marking new start at 76.40275603433227 app.js:274:25
Timeline edit cleared app.js:438:26
DOMException: String contains an invalid character
    VueJS 24
    markTimestamp http://localhost/plain/SRT-Maker/app.js:281
    handleKeyDown http://localhost/plain/SRT-Maker/app.js:402
vue.global.prod.js:5:20619
Tab pressed at: 77.48700604386902 app.js:216:21
Marked end for sub sub_1 at 77.48700604386902 app.js:223:29
TypeError: right-hand side of 'in' should be an object, got null
    VueJS 20
    markTimestamp http://localhost/plain/SRT-Maker/app.js:222
    handleKeyDown http://localhost/plain/SRT-Maker/app.js:402